
sudo: false

language: python

python:
          - 3.6

install:
          - pip install --user codecov

script:
          - coverage run --source=paop/ setup.py test 

after_success:
          - codecov 
