language: python
python: "3.6"
before_install: "pip install codecov"
install: "pip install ."
script: "coverage run --source=paop/ setup.py test"
after_success: "codecov --token=86462c9b-0bf0-465c-89af-4c457969491f"
