language: 
        - python
python: 
        - 3.6
install: 
        - pip install codecov
        - pip install sklearn
script: 
        - coverage run --source=paop/ setup.py test
after_success: 
        - codecov
