language: 
        - python
python: 
        - 3.6
addons:
        apt:
        sources:
                - ubuntu-toolchain-r-test
        packages:
                - libstdc++-4.9-dev
install: 
        - pip install -U pip
        - pip install codecov
        - pip install sklearn
        - pip install scipy
        - pip install keras
        - pip install tensorflow 

script: 
        - coverage run --source=paop/ setup.py test

after_success: 
        - codecov
