language: 
        - python
python: 
        - 3.6
install: 
        - pip install codecov
        - pip install sklearn
        - pip install scipy
        - pip install keras

script: 
        - coverage run --source=paop/ setup.py test

after_success: 
        - codecov
