language: 
        - python
python: 
        - 3.6
install: 
        - pip install codecov
        - pip install sklearn
        - pip install scipy
        - pip install keras
        - pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0a0-cp34-cp34m-linux_x86_64.whl;

script: 
        - coverage run --source=paop/ setup.py test

after_success: 
        - codecov
